// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7lhdcXez_ccxuB_56-65VIoVzpA3EXVs',
    appId: '1:501499781481:android:af9d0ca974aecfcbc21df8',
    messagingSenderId: '501499781481',
    projectId: 'to-do-list-287d6',
    storageBucket: 'to-do-list-287d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf1aHclnrBkMCD13PpvTNgnvaMa8CKQ_I',
    appId: '1:501499781481:ios:88a486bdcb4c842ac21df8',
    messagingSenderId: '501499781481',
    projectId: 'to-do-list-287d6',
    storageBucket: 'to-do-list-287d6.appspot.com',
    androidClientId: '501499781481-qe84l9ags3qsnpuoeujikh3pftolbkm4.apps.googleusercontent.com',
    iosClientId: '501499781481-k08dv3o0k689amettdg5uokqfjq13svo.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoListApp',
  );

}